package vista.privado.atomos.empresa;

import javax.swing.JDialog;

public class InHorarioEmpresa extends JDialog {

  /**
   * Creates new form InHorarioEmpresa
   */
  public InHorarioEmpresa() {
    initComponents();
    initDaySelection();
  }

  private void initDaySelection() {
    toggleDaySelection(tbtnLunes, horaInicioLunes, horaSalidaLunes);
    toggleDaySelection(tbtnMartes, horaInicioMartes, horaSalidaMartes);
    toggleDaySelection(tbtnMiercoles, horaInicioMiercoles, horaSalidaMiercoles);
    toggleDaySelection(tbtnJueves, horaInicioJueves, horaSalidaJueves);
    toggleDaySelection(tbtnViernes, horaInicioViernes, horaSalidaViernes);
    toggleDaySelection(tbtnSabado, horaInicioSabado, horaSalidaSabado);
    toggleDaySelection(tbtnDomingo, horaInicioDomingo, horaSalidaDomingo);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    barLunes = new javax.swing.JToolBar();
    tbtnLunes = new javax.swing.JToggleButton();
    horaInicioLunes = new vista.privado.atomos.InHora();
    horaSalidaLunes = new vista.privado.atomos.InHora();
    barMartes = new javax.swing.JToolBar();
    tbtnMartes = new javax.swing.JToggleButton();
    horaInicioMartes = new vista.privado.atomos.InHora();
    horaSalidaMartes = new vista.privado.atomos.InHora();
    barMIercoles = new javax.swing.JToolBar();
    tbtnMiercoles = new javax.swing.JToggleButton();
    horaInicioMiercoles = new vista.privado.atomos.InHora();
    horaSalidaMiercoles = new vista.privado.atomos.InHora();
    barJueves = new javax.swing.JToolBar();
    tbtnJueves = new javax.swing.JToggleButton();
    horaInicioJueves = new vista.privado.atomos.InHora();
    horaSalidaJueves = new vista.privado.atomos.InHora();
    barViernes = new javax.swing.JToolBar();
    tbtnViernes = new javax.swing.JToggleButton();
    horaInicioViernes = new vista.privado.atomos.InHora();
    horaSalidaViernes = new vista.privado.atomos.InHora();
    barSabado = new javax.swing.JToolBar();
    tbtnSabado = new javax.swing.JToggleButton();
    horaInicioSabado = new vista.privado.atomos.InHora();
    horaSalidaSabado = new vista.privado.atomos.InHora();
    barDomingo = new javax.swing.JToolBar();
    tbtnDomingo = new javax.swing.JToggleButton();
    horaInicioDomingo = new vista.privado.atomos.InHora();
    horaSalidaDomingo = new vista.privado.atomos.InHora();
    barOpciones = new javax.swing.JPanel();
    btnVaciar = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();
    btnActualizar = new javax.swing.JButton();

    getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

    barLunes.setRollover(true);

    tbtnLunes.setBackground(new java.awt.Color(0, 0, 0));
    tbtnLunes.setText("L");
    tbtnLunes.setFocusable(false);
    tbtnLunes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    tbtnLunes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    tbtnLunes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tbtnLunesActionPerformed(evt);
      }
    });
    barLunes.add(tbtnLunes);

    horaInicioLunes.setText(null);
    horaInicioLunes.setEnabled(false);
    barLunes.add(horaInicioLunes);

    horaSalidaLunes.setText(null);
    horaSalidaLunes.setEnabled(false);
    barLunes.add(horaSalidaLunes);

    getContentPane().add(barLunes);

    barMartes.setRollover(true);

    tbtnMartes.setBackground(new java.awt.Color(0, 0, 0));
    tbtnMartes.setText("M");
    tbtnMartes.setFocusable(false);
    tbtnMartes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    tbtnMartes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    tbtnMartes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tbtnMartesActionPerformed(evt);
      }
    });
    barMartes.add(tbtnMartes);

    horaInicioMartes.setText(null);
    horaInicioMartes.setEnabled(false);
    barMartes.add(horaInicioMartes);

    horaSalidaMartes.setText(null);
    horaSalidaMartes.setEnabled(false);
    barMartes.add(horaSalidaMartes);

    getContentPane().add(barMartes);

    barMIercoles.setRollover(true);

    tbtnMiercoles.setBackground(new java.awt.Color(0, 0, 0));
    tbtnMiercoles.setText("X");
    tbtnMiercoles.setFocusable(false);
    tbtnMiercoles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    tbtnMiercoles.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    tbtnMiercoles.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tbtnMiercolesActionPerformed(evt);
      }
    });
    barMIercoles.add(tbtnMiercoles);

    horaInicioMiercoles.setText(null);
    horaInicioMiercoles.setEnabled(false);
    barMIercoles.add(horaInicioMiercoles);

    horaSalidaMiercoles.setText(null);
    horaSalidaMiercoles.setEnabled(false);
    barMIercoles.add(horaSalidaMiercoles);

    getContentPane().add(barMIercoles);

    barJueves.setRollover(true);

    tbtnJueves.setBackground(new java.awt.Color(0, 0, 0));
    tbtnJueves.setText("J");
    tbtnJueves.setFocusable(false);
    tbtnJueves.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    tbtnJueves.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    tbtnJueves.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tbtnJuevesActionPerformed(evt);
      }
    });
    barJueves.add(tbtnJueves);

    horaInicioJueves.setText(null);
    horaInicioJueves.setEnabled(false);
    barJueves.add(horaInicioJueves);

    horaSalidaJueves.setText(null);
    horaSalidaJueves.setEnabled(false);
    barJueves.add(horaSalidaJueves);

    getContentPane().add(barJueves);

    barViernes.setRollover(true);

    tbtnViernes.setBackground(new java.awt.Color(0, 0, 0));
    tbtnViernes.setText("V");
    tbtnViernes.setFocusable(false);
    tbtnViernes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    tbtnViernes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    tbtnViernes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tbtnViernesActionPerformed(evt);
      }
    });
    barViernes.add(tbtnViernes);

    horaInicioViernes.setText(null);
    horaInicioViernes.setEnabled(false);
    barViernes.add(horaInicioViernes);

    horaSalidaViernes.setText(null);
    horaSalidaViernes.setEnabled(false);
    barViernes.add(horaSalidaViernes);

    getContentPane().add(barViernes);

    barSabado.setRollover(true);

    tbtnSabado.setBackground(new java.awt.Color(0, 0, 0));
    tbtnSabado.setText("S");
    tbtnSabado.setFocusable(false);
    tbtnSabado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    tbtnSabado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    tbtnSabado.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tbtnSabadoActionPerformed(evt);
      }
    });
    barSabado.add(tbtnSabado);

    horaInicioSabado.setText(null);
    horaInicioSabado.setEnabled(false);
    barSabado.add(horaInicioSabado);

    horaSalidaSabado.setText(null);
    horaSalidaSabado.setEnabled(false);
    barSabado.add(horaSalidaSabado);

    getContentPane().add(barSabado);

    barDomingo.setRollover(true);

    tbtnDomingo.setBackground(new java.awt.Color(0, 0, 0));
    tbtnDomingo.setText("D");
    tbtnDomingo.setFocusable(false);
    tbtnDomingo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    tbtnDomingo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    tbtnDomingo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tbtnDomingoActionPerformed(evt);
      }
    });
    barDomingo.add(tbtnDomingo);

    horaInicioDomingo.setText(null);
    horaInicioDomingo.setEnabled(false);
    barDomingo.add(horaInicioDomingo);

    horaSalidaDomingo.setText(null);
    horaSalidaDomingo.setEnabled(false);
    barDomingo.add(horaSalidaDomingo);

    getContentPane().add(barDomingo);

    btnVaciar.setText("Vaciar");

    btnCancelar.setText("Cancelar");

    btnActualizar.setText("Actualizar");

    javax.swing.GroupLayout barOpcionesLayout = new javax.swing.GroupLayout(barOpciones);
    barOpciones.setLayout(barOpcionesLayout);
    barOpcionesLayout.setHorizontalGroup(
      barOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(barOpcionesLayout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addComponent(btnVaciar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
        .addComponent(btnCancelar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
        .addComponent(btnActualizar)
        .addGap(25, 25, 25))
    );
    barOpcionesLayout.setVerticalGroup(
      barOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(barOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(btnCancelar)
        .addComponent(btnVaciar))
      .addComponent(btnActualizar)
    );

    getContentPane().add(barOpciones);
  }// </editor-fold>//GEN-END:initComponents

  private void tbtnLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnLunesActionPerformed
    toggleDaySelection(tbtnLunes, horaInicioLunes, horaSalidaLunes);
  }//GEN-LAST:event_tbtnLunesActionPerformed

  private void tbtnMartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnMartesActionPerformed
    toggleDaySelection(tbtnMartes, horaInicioMartes, horaSalidaMartes);
  }//GEN-LAST:event_tbtnMartesActionPerformed

  private void tbtnMiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnMiercolesActionPerformed
    toggleDaySelection(tbtnMiercoles, horaInicioMiercoles, horaSalidaMiercoles);
  }//GEN-LAST:event_tbtnMiercolesActionPerformed

  private void tbtnJuevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnJuevesActionPerformed
    toggleDaySelection(tbtnJueves, horaInicioJueves, horaSalidaJueves);
  }//GEN-LAST:event_tbtnJuevesActionPerformed

  private void tbtnViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnViernesActionPerformed
    toggleDaySelection(tbtnViernes, horaInicioViernes, horaSalidaViernes);
  }//GEN-LAST:event_tbtnViernesActionPerformed

  private void tbtnSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnSabadoActionPerformed
    toggleDaySelection(tbtnSabado, horaInicioSabado, horaSalidaSabado);
  }//GEN-LAST:event_tbtnSabadoActionPerformed

  private void tbtnDomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnDomingoActionPerformed
    toggleDaySelection(tbtnDomingo, horaInicioDomingo, horaSalidaDomingo);
  }//GEN-LAST:event_tbtnDomingoActionPerformed

  private void toggleDaySelection(javax.swing.JToggleButton button, vista.privado.atomos.InHora... hours) {
    boolean selected = button.isSelected();
    for (vista.privado.atomos.InHora h : hours) {
        h.setEnabled(selected);
        if (!selected) {
            h.setText("00:00:00");
        }
    }
  }

  public String getScheduleDescription() {
    StringBuilder sb = new StringBuilder();
    appendDay(sb, "L", tbtnLunes, horaInicioLunes, horaSalidaLunes);
    appendDay(sb, "M", tbtnMartes, horaInicioMartes, horaSalidaMartes);
    appendDay(sb, "X", tbtnMiercoles, horaInicioMiercoles, horaSalidaMiercoles);
    appendDay(sb, "J", tbtnJueves, horaInicioJueves, horaSalidaJueves);
    appendDay(sb, "V", tbtnViernes, horaInicioViernes, horaSalidaViernes);
    appendDay(sb, "S", tbtnSabado, horaInicioSabado, horaSalidaSabado);
    appendDay(sb, "D", tbtnDomingo, horaInicioDomingo, horaSalidaDomingo);
    
    if (sb.length() > 0) {
        sb.setLength(sb.length() - 2); // Remove trailing ", "
    } else {
        return "No hay horario seleccionado.";
    }
    return sb.toString();
  }

  private void appendDay(StringBuilder sb, String dayName, javax.swing.JToggleButton button, vista.privado.atomos.InHora start, vista.privado.atomos.InHora end) {
    if (button.isSelected()) {
        sb.append(dayName).append(": ");
        String s = start.getText();
        String e = end.getText();
        if (s == null || s.trim().isEmpty()) s = "00:00:00";
        if (e == null || e.trim().isEmpty()) e = "00:00:00";
        sb.append(s).append(" - ").append(e).append(", ");
    }
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToolBar barDomingo;
  private javax.swing.JToolBar barJueves;
  private javax.swing.JToolBar barLunes;
  private javax.swing.JToolBar barMIercoles;
  private javax.swing.JToolBar barMartes;
  private javax.swing.JPanel barOpciones;
  private javax.swing.JToolBar barSabado;
  private javax.swing.JToolBar barViernes;
  private javax.swing.JButton btnActualizar;
  private javax.swing.JButton btnCancelar;
  private javax.swing.JButton btnVaciar;
  private vista.privado.atomos.InHora horaInicioDomingo;
  private vista.privado.atomos.InHora horaInicioJueves;
  private vista.privado.atomos.InHora horaInicioLunes;
  private vista.privado.atomos.InHora horaInicioMartes;
  private vista.privado.atomos.InHora horaInicioMiercoles;
  private vista.privado.atomos.InHora horaInicioSabado;
  private vista.privado.atomos.InHora horaInicioViernes;
  private vista.privado.atomos.InHora horaSalidaDomingo;
  private vista.privado.atomos.InHora horaSalidaJueves;
  private vista.privado.atomos.InHora horaSalidaLunes;
  private vista.privado.atomos.InHora horaSalidaMartes;
  private vista.privado.atomos.InHora horaSalidaMiercoles;
  private vista.privado.atomos.InHora horaSalidaSabado;
  private vista.privado.atomos.InHora horaSalidaViernes;
  private javax.swing.JToggleButton tbtnDomingo;
  private javax.swing.JToggleButton tbtnJueves;
  private javax.swing.JToggleButton tbtnLunes;
  private javax.swing.JToggleButton tbtnMartes;
  private javax.swing.JToggleButton tbtnMiercoles;
  private javax.swing.JToggleButton tbtnSabado;
  private javax.swing.JToggleButton tbtnViernes;
  // End of variables declaration//GEN-END:variables
}
