/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package vista.privado.atomos.algoritmo;

import javax.swing.JComboBox;

/**
 *
 * @author ASUS 2
 */
public class InAlgoritmoBusqueda extends JComboBox {

  /**
   * Creates new form inAlgoritmoBusqueda
   */
  public InAlgoritmoBusqueda() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Búsqueda en Árbol", "Búsqueda Secuencial" }));
    setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Algoritmo de Búsqueda", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
