package vista.privado.atomos.algoritmo;

import javax.swing.JComboBox;

public class InAlgoritmoOrdenamiento extends JComboBox {

  /**
   * Creates new form inAlgoritmoOrdenamiento
   */
  public InAlgoritmoOrdenamiento() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bubble Sort", "Selection Sort", "Quick Sort", "Merge Sort" }));
    setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Algoritmo de Ordenamiento", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
