/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package vista.privado.atomos.algoritmo;

import javax.swing.JComboBox;

/**
 *
 * @author ASUS 2
 */
public class InCriterioBusqueda extends JComboBox {

  /**
   * Creates new form inCriterioBusqueda
   */
  public InCriterioBusqueda() {
    initComponents();
    cargarItems();
  }
  
  private void cargarItems() {
    removeAllItems();
    addItem("Por Placa");
    addItem("Por ID Ticket");
    addItem("Por Tipo de Vehículo");
    setSelectedIndex(0);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterio de Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
