package vista.privado.atomos.usuario;

import javax.swing.JFormattedTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import javax.swing.JOptionPane;

public class InDniUsuario extends JFormattedTextField {

  /**
   * Creates new form InDniNuevo
   */
  public InDniUsuario() {
    initComponents();
    configurarFormatoDNI();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setBackground(java.awt.Color.WHITE);
    setFont(new java.awt.Font("Segoe UI", 0, 12));
    setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));
  }// </editor-fold>//GEN-END:initComponents

  private void InDniNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InDniNuevoActionPerformed
    // manejador vacío; NetBeans GUI Builder puede editar este bloque
  }//GEN-LAST:event_InDniNuevoActionPerformed

    /**
     * Configura el formateador para DNI (máscara de 8 dígitos).
     */
    private void configurarFormatoDNI() {
    try {
      MaskFormatter mf = new MaskFormatter("########");
      mf.setPlaceholderCharacter(' ');
      setFormatterFactory(new DefaultFormatterFactory(mf));
    } catch (java.text.ParseException ex) {
      // No bloquear la carga del GUI: mostrar y seguir
      JOptionPane.showMessageDialog(this, "Error al configurar el formateador de DNI: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
  }

    /**
     * Obtiene el texto del DNI
     * @return Texto del DNI
     */
    @Override
    public String getText() {
    return super.getText();
  }

    /**
     * Establece el texto del DNI
     * @param text Texto a establecer
     */
    public void setText(String text) {
    super.setText(text);
  }

    /**
     * Limpia el campo de DNI
     */
    public void clear() {
    super.setText("");
  }

    /**
     * Valida que el DNI tenga 8 dígitos
     * @return true si válido, false en caso contrario
     */
    public boolean isValid() {
    try {
      String text = getText();
      return text != null && text.matches("^\\d{8}$");
    } catch (Exception e) {
      return false;
    }
  }

    @Override
    public void setEnabled(boolean enabled) {
    super.setEnabled(enabled);
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
