package vista.privado.atomos.usuario;

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ASUS 2
 */
public class InDvDniUsuario extends JFormattedTextField {

  /**
   * Creates new form InDvNuevo
   */
  public InDvDniUsuario() {
    initComponents();
    configurarFormatoDV();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
  }// </editor-fold>//GEN-END:initComponents

  private void InDvNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InDvNuevoActionPerformed
    // manejador vacío; NetBeans GUI Builder puede editar este bloque
  }//GEN-LAST:event_InDvNuevoActionPerformed

    /**
     * Configura el formateador para DV (1 carácter: dígito o letra según máscara '#').
     */
    private void configurarFormatoDV() {
    try {
      MaskFormatter mf = new MaskFormatter("#");
      mf.setPlaceholderCharacter(' ');
      setFormatterFactory(new DefaultFormatterFactory(mf));
    } catch (java.text.ParseException ex) {
      JOptionPane.showMessageDialog(this, "Error al configurar el formateador de DV: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
  }

    /**
     * Obtiene el texto del DV
     * @return Texto del DV
     */
    @Override
    public String getText() {
    return super.getText();
  }

    /**
     * Establece el texto del DV
     * @param text Texto a establecer
     */
    public void setText(String text) {
    super.setText(text);
  }

    /**
     * Limpia el campo de DV
     */
    public void clear() {
    super.setText("");
  }

    /**
     * Valida que el DV sea un solo carácter (dígito o letra según máscara aplicada)
     * @return true si válido, false en caso contrario
     */
    public boolean isValid() {
    try {
      String text = getText();
      return text != null && text.trim().length() == 1;
    } catch (Exception e) {
      return false;
    }
  }

    @Override
    public void setEnabled(boolean enabled) {
    super.setEnabled(enabled);
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
