package vista.privado.atomos;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import utilidad.FechaFormatter;

/**
 * Bean JFormattedTextField para Fecha con formateador personalizado.
 */
public class InFecha extends JFormattedTextField {

  /**
   * Creates new form InFecha
   */
  public InFecha() {
    initComponents();
    // Configurar el formateador personalizado y placeholder inicial
    configurarFormatoFecha();
    // Placeholder visible: el usuario pidió formato siempre visible como 00/00/0000
    setText("00/00/0000");
    // Posicionar caret al inicio cuando el campo reciba foco y tenga el placeholder
    addFocusListener(new FocusAdapter() {
      @Override
      public void focusGained(FocusEvent evt) {
        if ("00/00/0000".equals(getText())) {
          setCaretPosition(0);
        }
      }
    });
  }

  /**
   * Configura el formateador de fecha (dd/MM/yyyy).
   */
  private void configurarFormatoFecha() {
    try {
      setFormatterFactory(new DefaultFormatterFactory(new FechaFormatter()));
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, "Error al configurar el formateador de Fecha: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
  }// </editor-fold>//GEN-END:initComponents

  private void InFechaNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InFechaNuevoActionPerformed
    // manejador vacío; NetBeans GUI Builder puede editar este bloque
  }//GEN-LAST:event_InFechaNuevoActionPerformed

  /**
   * Obtiene el texto de la fecha
   * @return texto en formato dd/MM/yyyy o cadena vacía
   */
  @Override
  public String getText() {
    return super.getText();
  }

  /**
   * Establece el texto de la fecha
   */
  @Override
  public void setText(String text) {
    super.setText(text);
  }

  /**
   * Limpia el campo
   */
  public void clear() {
    super.setText("");
  }

  /**
   * Valida la fecha completa (dd/MM/yyyy) si está rellenada
   */
  public boolean isValid() {
    try {
      String t = getText();
      if (t == null || t.trim().isEmpty()) return false;
      java.time.format.DateTimeFormatter dtf = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
      java.time.LocalDate.parse(t, dtf);
      return true;
    } catch (Exception e) {
      return false;
    }
  }

  @Override
  public void setEnabled(boolean enabled) {
    super.setEnabled(enabled);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
