package vista.privado.atomos;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import utilidad.HoraFormatter;

/**
 * Bean JFormattedTextField para Hora con formateador personalizado.
 */
public class InHora extends JFormattedTextField {

  /**
   * Creates new form InHoraNuevo
   */
  public InHora() {
    initComponents();
    configurarFormatoHora();
    // Mostrar placeholder y comportamiento de foco similar a InFechaNuevo
    setText("00:00:00");
    addFocusListener(new FocusAdapter() {
      @Override
      public void focusGained(FocusEvent evt) {
        if ("00:00:00".equals(getText())) {
          setCaretPosition(0);
        }
      }
    });
  }

  private void configurarFormatoHora() {
    try {
      setFormatterFactory(new DefaultFormatterFactory(new HoraFormatter()));
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, "Error al configurar el formateador de Hora: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jDialog1 = new javax.swing.JDialog();

    javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
    jDialog1.getContentPane().setLayout(jDialog1Layout);
    jDialog1Layout.setHorizontalGroup(
      jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 488, Short.MAX_VALUE)
    );
    jDialog1Layout.setVerticalGroup(
      jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 399, Short.MAX_VALUE)
    );

    setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
    setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm:ss"))));
    setToolTipText("");
  }// </editor-fold>//GEN-END:initComponents

  private void InHoraNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InHoraNuevoActionPerformed
    // manejador vacío; NetBeans GUI Builder puede editar este bloque
  }//GEN-LAST:event_InHoraNuevoActionPerformed

  @Override
  public String getText() {
    return super.getText();
  }

  @Override
  public void setText(String text) {
    super.setText(text);
  }

  public void clear() {
    super.setText("");
  }

  public boolean isValid() {
    try {
      String t = getText();
      if (t == null || t.trim().isEmpty()) return false;
      java.time.format.DateTimeFormatter dtf = java.time.format.DateTimeFormatter.ofPattern("HH:mm:ss");
      java.time.LocalTime.parse(t, dtf);
      return true;
    } catch (Exception e) {
      return false;
    }
  }

  @Override
  public void setEnabled(boolean enabled) {
    super.setEnabled(enabled);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JDialog jDialog1;
  // End of variables declaration//GEN-END:variables
}
