/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/BeanForm.java to edit this template
 */
package vista.privado.atomos;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFormattedTextField;
import javax.swing.Timer;

/**
 *
 * @author ASUS 2
 */
public class Reloj extends JFormattedTextField {

  /**
   * Creates new form RelojNuevo
   */
  public Reloj() {
    initComponents();
    // Inicializa y arranca el timer que actualiza cada segundo
    actualizarHora();
    timer = new Timer(1000, e -> actualizarHora());
    timer.start();
  }

  private final DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
  private final Timer timer;

  private void actualizarHora() {
    LocalDateTime ahora = LocalDateTime.now();
    // Mostrar en el propio JFormattedTextField
    setText(ahora.format(formato));
  }

  /**
   * Detiene el reloj (timer)
   */
  public void detenerReloj() {
    if (timer != null && timer.isRunning()) {
      timer.stop();
    }
  }

  @Override
  public void removeNotify() {
    super.removeNotify();
    detenerReloj();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Fecha y Hora Actual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
